# Generated by Django 6.0.2 on 2026-02-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_userorder_address'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi buyurtma'), ('waiting', 'Kutulmoqda...'), ('in_progress', 'Jarayonda...'), ('waiting_pay', 'Tolov qilish Kutilmoqda...'), ('delivering', 'Yetkazib berilmoqda...'), ('deliveried', 'Yetkazib berilgan.'), ('complated', 'Tugallangan.'), ('cancalled_by_customer', 'Mijoz tomondan bekor qilingan'), ('cancalled_by_seller', 'Sotuvchi tomonidan bekor qilingan')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userorder',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.useraddress'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('click', 'Click orqali'), ('payme', 'Payme orqali'), ('cart', 'Plastik orqali'), ('other', 'boshqa tolov turi orqali')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.userorder')),
            ],
        ),
    ]
